---
development:
  dialect: postgres
  database: expense_management
  user: postgres
  password: postgres
  host: 127.0.0.1
  port: 5430

staging:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/ops_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/ops_production?sslmode=disable"}}
